create-offline-pinned-pipelines creates artifacts
Instead of just making an offline version of pcf-pipelines pinned to
particular versions, create the required tarballs as well.

The final job, create-pcf-pipelines-combined, can be used to create a
single tarball that collects all the required resources into a single
artifact. This job is optional.

[#148074921]

diff --git a/create-offline-pinned-pipelines/pipeline.yml b/create-offline-pinned-pipelines/pipeline.yml
--- a/create-offline-pinned-pipelines/pipeline.yml
+++ b/create-offline-pinned-pipelines/pipeline.yml
@@ -6,7 +6,7 @@ resource_types:
     tag: latest-final
 
 resources:
-- name: operations-manager
+- name: operations-manager-pivnet
   type: pivnet
   source:
     api_token: {{pivnet_token}}
@@ -14,13 +14,41 @@ resources:
     product_version: {{operations_manager_regex}}
     sort_by: semver
 
-- name: elastic-runtime
+- name: operations-manager-s3
+  type: s3
+  source:
+    access_key_id: {{s3_access_key_id}}
+    secret_access_key: {{s3_secret_access_key}}
+    endpoint: {{s3_endpoint}}
+    bucket: {{s3_bucket}}
+    regexp: "ops-manager/ops-manager-(.*).tar"
+
+- name: elastic-runtime-pivnet
   type: pivnet
   source:
+    api_token: {{pivnet_token}}
     product_slug: elastic-runtime
     product_version: {{elastic_runtime_regex}}
     sort_by: semver
-    api_token: {{pivnet_token}}
+
+- name: elastic-runtime-s3
+  type: s3
+  source:
+    access_key_id: {{s3_access_key_id}}
+    secret_access_key: {{s3_secret_access_key}}
+    endpoint: {{s3_endpoint}}
+    bucket: {{s3_bucket}}
+    regexp: "elastic-runtime/elastic-runtime-(.*).tar"
+
+- name: stemcells-s3
+  type: s3
+  source:
+    access_key_id: {{s3_access_key_id}}
+    secret_access_key: {{s3_secret_access_key}}
+    endpoint: {{s3_endpoint}}
+    bucket: {{s3_bucket}}
+    regexp: "stemcells/bosh-stemcell-(.*)-.*.tgz"
+    disable_ssl: false
 
 - name: czero-cflinuxfs2
   type: docker-image
@@ -28,11 +56,42 @@ resources:
     repository: czero/cflinuxfs2
     tag: latest
 
+- name: czero-cflinuxfs2-s3
+  type: s3
+  source:
+    access_key_id: {{s3_access_key_id}}
+    secret_access_key: {{s3_secret_access_key}}
+    endpoint: {{s3_endpoint}}
+    bucket: {{s3_bucket}}
+    regexp: "czero-cflinuxfs2/czero-cflinuxfs2-(.*)-(.*).tgz"
+
+- name: czero-cflinuxfs2-version
+  type: semver
+  source:
+    initial_version: 0.0.0
+    driver: s3
+    bucket: {{s3_bucket}}
+    key: "czero-cflinuxfs2/version"
+    access_key_id: {{s3_access_key_id}}
+    secret_access_key: {{s3_secret_access_key}}
+    endpoint: {{s3_endpoint}}
+
 - name: pcf-pipelines-tarball
   type: pivnet
   source:
     api_token: {{pivnet_token}}
     product_slug: pcf-automation
+
+- name: pcf-pipelines-combined-version
+  type: semver
+  source:
+    initial_version: 0.0.0
+    driver: s3
+    bucket: {{s3_bucket}}
+    key: "pcf-pipelines-combined-version/version"
+    access_key_id: {{s3_access_key_id}}
+    secret_access_key: {{s3_secret_access_key}}
+    endpoint: {{s3_endpoint}}
 
 - name: pcf-pipelines-offline-pinned-tarball
   type: s3
@@ -41,7 +100,16 @@ resources:
     secret_access_key: {{s3_secret_access_key}}
     endpoint: {{s3_endpoint}}
     bucket: {{s3_bucket}}
-    regexp: "pcf-pipelines-offline-pinned-tarball/pcf-pipelines-offline-pinned-v(.*).tar"
+    regexp: "pcf-pipelines-offline-pinned-tarball/pcf-pipelines-offline-pinned-v(.*).tgz"
+
+- name: pcf-pipelines-combined
+  type: s3
+  source:
+    access_key_id: {{s3_access_key_id}}
+    secret_access_key: {{s3_secret_access_key}}
+    endpoint: {{s3_endpoint}}
+    bucket: {{s3_bucket}}
+    regexp: "pcf-pipelines-combined/pcf-pipelines-combined-(.*).tar"
 
 - name: fly
   type: github-release
@@ -56,12 +124,12 @@ jobs:
   plan:
   - aggregate:
     - get: czero-cflinuxfs2
-    - get: operations-manager
-      params:
-        globs: ["*vsphere*"]
-    - get: elastic-runtime
-      params:
-        globs: ["*.pivotal"]
+    - get: czero-cflinuxfs2-version
+      params: { bump: major }
+    - get: operations-manager-pivnet
+      params: { globs: [] }
+    - get: elastic-runtime-pivnet
+      params: { globs: [] }
     - get: fly
     - do:
       - get: pcf-pipelines-tarball
@@ -78,7 +146,7 @@ jobs:
           - name: pcf-pipelines
           run:
            path: sh
-           args: ["-c", "tar -xvf pcf-pipelines-tarball/*.tgz"]
+           args: ["-c", "tar -xvzf pcf-pipelines-tarball/*.tgz"]
   - task: create-pipelines
     config:
       platform: linux
@@ -87,8 +155,9 @@ jobs:
         source: {repository: czero/cflinuxfs2}
       inputs:
       - name: czero-cflinuxfs2
-      - name: operations-manager
-      - name: elastic-runtime
+      - name: czero-cflinuxfs2-version
+      - name: operations-manager-pivnet
+      - name: elastic-runtime-pivnet
       - name: pcf-pipelines-tarball
       - name: pcf-pipelines
       - name: fly
@@ -111,22 +180,27 @@ jobs:
 
           cp pcf-pipelines/install-pcf/vsphere/offline/params.yml pcf-pipelines-offline-pinned/install-pcf/vsphere/params.yml
 
-          opsman_version=$(cat operations-manager/metadata.json | jq --raw-output '.Release.Version')
-          ert_version=$(cat elastic-runtime/metadata.json | jq --raw-output '.Release.Version')
+          opsman_version=$(cat operations-manager-pivnet/metadata.json | jq --raw-output '.Release.Version')
+          ert_version=$(cat elastic-runtime-pivnet/metadata.json | jq --raw-output '.Release.Version')
+          czero_cflinuxfs2_version=$(cat czero-cflinuxfs2-version/version)
 
           cat > pin-resource-gets.yml <<EOF
           - op: add
             path: /jobs/get=pivnet-opsman-product/version
             value:
-              path: "ops-manager/ops-manager-${opsman_version}.tgz"
+              path: "ops-manager/ops-manager-${opsman_version}.tar"
           - op: add
             path: /jobs/get=pcf-ops-manager/version
             value:
-              path: "ops-manager/ops-manager-${opsman_version}.tgz"
+              path: "ops-manager/ops-manager-${opsman_version}.tar"
           - op: add
             path: /jobs/get=pivnet-product/version
             value:
-              path: "elastic-runtime/elastic-runtime-${ert_version}.tgz"
+              path: "elastic-runtime-pivnet/elastic-runtime-${ert_version}.tar"
+          - op: replace
+            path: /jobs/regexp=czero-cflinuxfs2~1czero-cflinuxfs2-(.*)-.*.tgz
+            value:
+              path: "czero-cflinuxfs2/czero-cflinuxfs2-(${czero_cflinuxfs2_version})-.*.tgz"
           EOF
 
           fly fmt -c <(
@@ -134,12 +208,219 @@ jobs:
           ) > pcf-pipelines-offline-pinned/install-pcf/vsphere/pipeline.yml
 
           pcf_pipelines_version=$(cat pcf-pipelines-tarball/metadata.json | jq --raw-output '.Release.Version')
-          tar \
-          --create \
-          --verbose \
-          --directory pcf-pipelines-offline-pinned . \
-          --file "pcf-pipelines-offline-pinned-tarball/pcf-pipelines-offline-pinned-${pcf_pipelines_version}.tar"
+
+          tar czv \
+          -f "pcf-pipelines-offline-pinned-tarball/pcf-pipelines-offline-pinned-${pcf_pipelines_version}.tgz" \
+          -C pcf-pipelines-offline-pinned \
+          .
   - put: pcf-pipelines-offline-pinned-tarball
     params:
-      file: "pcf-pipelines-offline-pinned-tarball/*.tar"
+      file: "pcf-pipelines-offline-pinned-tarball/*.tgz"
 
+- name: create-ops-manager-tarball
+  plan:
+  - get: pcf-pipelines-offline-pinned-tarball
+    passed: [create-offline-pinned-pipelines]
+  - get: operations-manager-pivnet
+    passed: [create-offline-pinned-pipelines]
+    trigger: true
+    params:
+      globs: ["*.ova"]
+  - task: create-tarball
+    config:
+      platform: linux
+      image_resource:
+        type: docker-image
+        source:
+          repository: czero/cflinuxfs2
+      inputs:
+      - name: operations-manager-pivnet
+      outputs:
+      - name: ops-manager-tarball
+      run:
+        path: bash
+        args:
+        - -c
+        - |
+          set -eu
+
+          version=$(cat operations-manager-pivnet/metadata.json | jq --raw-output '.Release.Version')
+
+          echo "Creating tarball with version ${version}..."
+          tar cf "ops-manager-tarball/ops-manager-${version}.tar" -C operations-manager-pivnet .
+  - put: operations-manager-s3
+    params:
+      file: "ops-manager-tarball/ops-manager-*.tar"
+
+- name: create-elastic-runtime-tarball
+  plan:
+  - get: pcf-pipelines-offline-pinned-tarball
+    passed: [create-offline-pinned-pipelines]
+  - get: elastic-runtime-pivnet
+    passed: [create-offline-pinned-pipelines]
+    trigger: true
+    params:
+      globs: ["*.pivotal"]
+  - task: create-tarball
+    config:
+      platform: linux
+      image_resource:
+        type: docker-image
+        source:
+          repository: czero/cflinuxfs2
+      inputs:
+      - name: elastic-runtime-pivnet
+      outputs:
+      - name: elastic-runtime-tarball
+      - name: stemcell-tarball
+      params:
+        PIVNET_API_TOKEN: {{pivnet_token}}
+      run:
+        path: bash
+        args:
+        - -c
+        - |
+          set -eu
+
+          stemcell_version=$(
+            cat ./elastic-runtime-pivnet/metadata.json |
+            jq --raw-output \
+              '
+              [
+                .Dependencies[]
+                | select(.Release.Product.Name | contains("Stemcells"))
+                | .Release.Version
+              ] | sort | last // empty
+              '
+          )
+
+          if [ -z "$stemcell_version" ]; then
+            echo "Expected to find stemcell version in ./elastic-runtime-pivnet/metadata.json, did not."
+            exit 1
+          fi
+
+          echo "Downloading stemcell $stemcell_version"
+          pivnet-cli login --api-token="$PIVNET_API_TOKEN"
+          pivnet-cli download-product-files -p stemcells -r $stemcell_version -g "*vsphere*" --accept-eula
+
+          stemcell_path=$(find . -name *bosh-stemcell-*.tgz)
+
+          if [ ! -f "$stemcell_path" ]; then
+            echo "Stemcell file not found!"
+            exit 1
+          fi
+
+          mv $stemcell_path stemcell-tarball/
+
+          version=$(cat elastic-runtime-pivnet/metadata.json | jq --raw-output '.Release.Version')
+
+          tar cvf "elastic-runtime-tarball/elastic-runtime-${version}.tar" -C elastic-runtime-pivnet .
+  - put: elastic-runtime-s3
+    params:
+      file: "elastic-runtime-tarball/elastic-runtime-*.tar"
+  - put: stemcells-s3
+    params:
+      file: "stemcell-tarball/*.tgz"
+
+- name: create-czero-cflinuxfs2-tarball
+  plan:
+  - aggregate:
+    - get: pcf-pipelines-offline-pinned-tarball
+      passed: [create-offline-pinned-pipelines]
+    - get: czero-cflinuxfs2
+      trigger: true
+      passed: [create-offline-pinned-pipelines]
+    - get: czero-cflinuxfs2-version
+      params: {bump: major}
+  - task: create-tarball
+    config:
+      platform: linux
+      image_resource:
+        type: docker-image
+        source:
+          repository: busybox
+      inputs:
+      - name: czero-cflinuxfs2
+      - name: czero-cflinuxfs2-version
+      outputs:
+      - name: czero-cflinuxfs2-tarball
+      run:
+        path: sh
+        args:
+        - -c
+        - |
+          set -eu
+
+          version=$(cat czero-cflinuxfs2-version/version)
+          digest=$(cat czero-cflinuxfs2/digest)
+
+          echo "Creating tarball with version ${version}-${digest}..."
+          tar cf "czero-cflinuxfs2-tarball/czero-cflinuxfs2-${version}-${digest}.tgz" -C czero-cflinuxfs2 .
+  - put: czero-cflinuxfs2-version
+    params: {bump: major}
+  - put: czero-cflinuxfs2-s3
+    params:
+      file: "czero-cflinuxfs2-tarball/czero-cflinuxfs2-*.tgz"
+
+- name: create-pcf-pipelines-combined
+  plan:
+  - aggregate:
+    - get: pcf-pipelines-offline-pinned-tarball
+      passed:
+      - create-czero-cflinuxfs2-tarball
+      - create-ops-manager-tarball
+      - create-elastic-runtime-tarball
+    - get: pcf-pipelines-combined-version
+      params: { bump: major }
+    - get: czero-cflinuxfs2-s3
+      passed: [create-czero-cflinuxfs2-tarball]
+    - get: operations-manager-s3
+      passed: [create-ops-manager-tarball]
+    - get: elastic-runtime-s3
+      passed: [create-elastic-runtime-tarball]
+    - get: stemcells-s3
+      passed: [create-elastic-runtime-tarball]
+  - task: create-tarball
+    config:
+      platform: linux
+      image_resource:
+        type: docker-image
+        source: {repository: czero/cflinuxfs2}
+      inputs:
+      - name: pcf-pipelines-offline-pinned-tarball
+      - name: pcf-pipelines-combined-version
+      - name: czero-cflinuxfs2-s3
+      - name: operations-manager-s3
+      - name: elastic-runtime-s3
+      - name: stemcells-s3
+      outputs:
+      - name: pcf-pipelines-combined
+      run:
+        path: bash
+        args:
+        - -c
+        - |
+          mkdir -p pcf-pipelines-combined-contents
+
+          tar xzf pcf-pipelines-offline-pinned-tarball/*.tgz -C pcf-pipelines-combined-contents
+
+          mv \
+            czero-cflinuxfs2-s3/*.tar \
+            operations-manager/*.tar \
+            elastic-runtime/*.tar \
+            stemcells-s3/*.tar \
+            pcf-pipelines-combined-contents
+
+          shasum pcf-pipelines-combined-contents > pcf-pipelines-combined-contents/MANIFEST.MF
+
+          version=$(cat pcf-pipelines-combined-version/version)
+
+          tar cv \
+          -f "pcf-pipelines-combined/pcf-pipelines-combined-${version}.tar" \
+          -C pcf-pipelines-combined-contents \
+          .
+  - put: pcf-pipelines-combined
+    params:
+      file: "pcf-pipelines-combined/*.tar"
+  - put: pcf-pipelines-combined-version
+    params: { bump: major }
